# ProtoPathway Configuration File

# Base paths
base_dir : "C:/Users/Amaya/Documents/PhD/ProtoPathway"
output_dir: "${base_dir}/output"

# Dataset name
dataset_name: "R4RA" # choices: ['R4RA', 'Sjogren']
label: 'label'
label_dict: {'0': 'Pauci-Immune', '1': 'Lymphoid/Myeloid'}
n_classes: 2
patient_id: 'Patient_ID'


# Input files
input:
  dir: "${base_dir}/input_files"
  gtf_file: "${base_dir}/input_files/Homo_sapiens.GRCh38.113.gtf"
  gene_expression: "${base_dir}/input_files/gene_expression_${dataset_name}_cpm.csv"
  reactome_gmt: "${base_dir}/input_files/ReactomePathways.gmt"
  reactome_relations: "${base_dir}/input_files/ReactomePathwaysRelation.txt"
  reactome_pathways: "${base_dir}/input_files/ReactomePathways.txt"
  patient_labels: "patient_labels_${dataset_name}.csv"

# Output directory structure
output:
  data:
    dir: "${output_dir}/processed_data"
    gene_annotations: "${output_dir}/processed_data/gene_annotations.csv"
    filtered_genes: "${output_dir}/processed_data/gene_expression_filtered_${dataset_name}.csv"
    reactome_pathways: "${output_dir}/processed_data/reactome_pathways_gene_lists.csv"
    final_pathways: "${output_dir}/processed_data/final_filtered_reactome_pathways.csv"
    removed_pathways_csv: "${output_dir}/processed_data/removed_pathways_report.csv"
    removed_pathways_md: "${output_dir}/processed_data/removed_pathways_report.md"
  figures:
    dir: "${output_dir}/figures/"
  reports:
    dir: "${output_dir}/reports/"
    removed_pathways: "${output_dir}/reports/removed_pathways_report.csv"
    removed_pathways_md: "${output_dir}/reports/removed_pathways_report.md"

parameters:
  gene_expression:
    threshold: 1         # Minimum expression level
    min_proportion: 0.10 # Minimum proportion of patients with expression
    variance_proportion: 0.80 # Top proportion of variable genes to keep

pathway:
  min_genes: 0        # Minimum number of genes in a pathway
  max_genes: 3000       # Maximum number of genes in a pathway
  similarity_threshold: 1.0 # Threshold for redundant pathways
  target_depth: 5      # Target pathway depth in Reactome hierarchy
  max_visualization: 100 # Maximum number of pathways to visualize in hypergraph

# Dataset configurations
dataset:
  patch_size: 224
  overlap: 0
  coverage: 0.4 # percent of tissue coverage in the patch
  slide_level: 2
  mask_level: 2
  patch_batch_size: 10
  train_fraction: 0.8
  val_fraction: 0.20
  stain_used: 'all' # RA choices: ['all', 'H&E', 'CD68', 'CD138', 'CD20']
  split_seed: 42
  stratified_splits: 5

# Parsing configurations
parsing:
  patient_ID: 'img.split("_")[0]' # "Patient123_stain.tiff" -> Patient123
  stain: 'img.split("_")[1]' # "Patient123_stain.tiff" -> stain
  stain_types: {'NA': 0, 'H&E': 1, 'CD68': 2, 'CD138': 3, 'CD20': 4} # RA stain types
  stain_colors: {'H&E': 'tab:pink', 'CD68': 'tab:brown', 'CD20': 'tab:blue', 'CD138': 'tab:orange'}
  edge_types: { 'RAG': 0, 'KNN': 1, 'BOTH': 2 }
  edge_colors: { 'RAG': 'red', 'KNN': 'dodgerblue', 'BOTH': 'blueviolet' }

# Graph configurations
graph:
  K: 7
  graph_mode: "krag"
  encoding_size: 20
  positional_encoding: true

GNN:
  num_layers: 4
  convolution: "GAT"
  use_node_embedding: false
  use_edge_embedding: false
  attention_heads: 2
  use_attention: true
  pooling_ratio: 0.7

training:
  hidden_dim: 512
  learning_rate: 0.001
  dropout_rate: 0.5
  num_epochs: 100
  L2_norm: 0
  L1_norm: 0
  batch_size: 1
  slide_batch: 1
  num_workers: 0
  checkpoint: true
  seed: 42
  weight_type: 'accuracy' # choices: ['accuracy', 'loss', 'auc']

scheduler:
  use: false  # toggle this to true when you want to activate it
  type: step
  step: 10
  gamma: 0.1
  patience: 5
  min_lr: 1e-6

# Visualization configurations
visualization:
  test_fold: 0
  test_ids: null
  specific_ids: false

model:
  name: 'Hypergraph' # choices ['MLP', 'Hypergraph']

# Execution flags
execution:
  ge_preprocess: false
  wsi_preprocess: false
  wsi_segmentation: false
  wsi_embedding: false
  create_splits: false
#  compute_rwpe: false
  cross_validation: false
  full_train: true
  test: false
  visualise: false

# Embedding models configs & paths
embedding_net:
  UNI:
    size: 1024
    weight_path: ""
    class: "UNI_embedding"

# Mapping of class names to module paths
embedding_class:
  UNI_embedding: "models.embedding_models.UNI_embedding"