"""
Spatial Visualization: Prototype and Pathway Overlays on WSI.

Generates publication-quality spatial heatmaps by mapping model attention
signals back to tissue coordinates. Reconstructs a canvas from either
a downloaded WSI (via OpenSlide) or a blank coordinate-based layout,
then overlays:

    1. Prototype assignment map — each patch colored by its assigned
       prototype, with opacity proportional to gate weight (Signal E).

    2. Risk-aware pathway overlay (Option C) — each patch colored by
       the top risk-direction-relevant pathway for its prototype, using
       per-fold rank analysis results. High-risk patients show each
       prototype's top high-risk-ranked pathway; low-risk patients show
       the top low-risk-ranked pathway.

    3. Single-pathway attention heatmap — continuous intensity map for
       one selected pathway across all patches, analogous to a
       computational IHC stain.

Coordinate loading (two paths, in priority order):
    1. Preprocessed .pt files (preferred) — when preprocess_wsi.py saves
       coords alongside features, we load everything from a single .pt
       file with guaranteed index alignment.
    2. Original h5 files (fallback) — re-reads coords from the h5 files,
       mimicking the preprocessing concatenation order. More fragile.

Usage:
    from utils.visualization.spatial_heatmaps import generate_patient_spatial_viz

    generate_patient_spatial_viz(
        patient_id='TCGA-A6-2671',
        attention_data=attention_by_patient['TCGA-A6-2671'],
        pathway_names=pathway_names,
        fold_analysis_dir='figures/per_fold/fold_0/analysis/',
        output_dir='figures/spatial/TCGA-A6-2671/',
        risk_group='High Risk',
        wsi_features_dir='processed/COADREAD/wsi_features_per_patient/',
        wsi_path='/path/to/TCGA-A6-2671-01Z-00-DX1.svs',  # optional
    )
"""

import os
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import Normalize

from utils.visualization.prototype_panels import (
    extract_exemplar_patches,
    plot_prototype_exemplars,
    plot_overlay_exemplar_strip,
)

logger = logging.getLogger(__name__)

# Try importing OpenSlide (optional dependency for WSI reading)
try:
    import openslide
    HAS_OPENSLIDE = True
except ImportError:
    HAS_OPENSLIDE = False

SAVE_MULTI_FORMAT = ''
_OUTPUT_FORMATS = ['pdf', 'svg', 'png']

def _save_multi_format(fig, base_path, dpi=300, formats=None):
    """Save a matplotlib figure in PDF, SVG, and PNG."""
    if formats is None:
        formats = _OUTPUT_FORMATS
    base = Path(base_path)
    base.parent.mkdir(parents=True, exist_ok=True)
    for fmt in formats:
        fig.savefig(
            str(base) + f'.{fmt}', dpi=dpi,
            bbox_inches='tight', facecolor='white',
        )

# =====================================================================
# 0. Coordinate spacing detection
# =====================================================================

def infer_coord_spacing(coords: np.ndarray) -> int:
    """
    Infer the patch footprint in coordinate space from the coord grid.

    UNI-2h extracts 256×256 patches at 20x, but h5 coords are at
    level 0 (often 40x), so adjacent patches are spaced 512 apart.
    This function detects that spacing automatically.

    Strategy: compute the smallest non-zero difference along each axis
    across all patch pairs. The mode of these differences is the grid
    step.

    Args:
        coords: [N, 2] array of (x, y) top-left coordinates.

    Returns:
        Estimated patch footprint in coordinate space (e.g., 512).
    """
    if len(coords) < 2:
        return 256  # fallback

    # Get unique sorted values per axis
    unique_x = np.unique(coords[:, 0])
    unique_y = np.unique(coords[:, 1])

    # Compute minimum positive differences
    diffs = []
    if len(unique_x) > 1:
        dx = np.diff(unique_x)
        diffs.extend(dx[dx > 0].tolist())
    if len(unique_y) > 1:
        dy = np.diff(unique_y)
        diffs.extend(dy[dy > 0].tolist())

    if not diffs:
        return 256  # fallback

    # Mode of differences = grid spacing
    from collections import Counter
    spacing = Counter(diffs).most_common(1)[0][0]

    return int(spacing)


def _build_distinct_colormap(n: int) -> Dict[int, Tuple]:
    """
    Build a palette of n maximally distinct RGB colors.

    First 20 are hand-picked for perceptual separation (no pastel
    variants of the same hue). Beyond 20, additional colors are
    generated by evenly sampling HSV hue at high saturation.

    Args:
        n: Number of distinct colors needed.

    Returns:
        Dict mapping index -> (R, G, B) as uint8 tuples.
    """
    # 20 hand-picked colours: high saturation, spread across hue space,
    # avoiding adjacent-similar pairs that plague tab20
    _BASE = [
        (230,  25,  75),  # red
        ( 60, 180,  75),  # green
        (  0, 130, 200),  # blue
        (255, 225,  25),  # yellow
        (245, 130,  48),  # orange
        (145,  30, 180),  # purple
        ( 70, 240, 240),  # cyan
        (240,  50, 230),  # magenta
        (210, 245,  60),  # lime
        (250, 190, 212),  # pink
        (  0, 128, 128),  # teal
        (220, 190, 255),  # lavender
        (170, 110,  40),  # brown
        (255, 250, 200),  # beige
        (128,   0,   0),  # maroon
        (170, 255, 195),  # mint
        (128, 128,   0),  # olive
        (255, 215, 180),  # apricot
        (  0,   0, 128),  # navy
        (128, 128, 128),  # grey
    ]

    if n <= len(_BASE):
        return {i: _BASE[i] for i in range(n)}

    # Beyond 20: fill with HSV samples at S=0.9, V=0.9
    import colorsys
    palette = {i: _BASE[i] for i in range(len(_BASE))}
    extra_needed = n - len(_BASE)
    for j in range(extra_needed):
        hue = j / extra_needed
        r, g, b = colorsys.hsv_to_rgb(hue, 0.9, 0.9)
        palette[len(_BASE) + j] = (int(r * 255), int(g * 255), int(b * 255))

    return palette


# =====================================================================
# 1. Slide data loading and coordinate recovery
# =====================================================================

def find_patient_h5_files(
    patient_id: str,
    h5_dir: str,
    slide_type_filter: str = 'DX',
    max_slides: int = 2,
) -> List[Path]:
    """
    Find h5 feature files for a patient, mimicking preprocess_wsi.py logic.

    Returns files in sorted order, truncated to the largest `max_slides`
    by patch count — matching the preprocessing concatenation order.

    Args:
        patient_id: TCGA patient ID (e.g., 'TCGA-A6-2671').
        h5_dir: Directory containing h5 files.
        slide_type_filter: Slide type substring filter (e.g., 'DX').
        max_slides: Maximum slides per patient (must match preprocessing).

    Returns:
        List of h5 file paths in concatenation order.
    """
    h5_dir = Path(h5_dir)
    candidates = []

    for ext in ['.h5', '.hdf5']:
        for f in h5_dir.glob(f'*{ext}'):
            # Check patient ID is in filename
            if patient_id not in f.name:
                continue
            # Apply slide type filter
            if slide_type_filter and slide_type_filter not in f.name:
                continue
            candidates.append(f)

    if not candidates:
        raise FileNotFoundError(
            f"No h5 files found for patient {patient_id} in {h5_dir}"
        )

    # Sort by patch count descending (matching preprocess_wsi.py truncation)
    candidates_with_size = []
    for f in candidates:
        with h5py.File(f, 'r') as h5:
            n_patches = _get_h5_feature_count(h5)
        candidates_with_size.append((f, n_patches))

    candidates_with_size.sort(key=lambda x: x[1], reverse=True)
    selected = [f for f, _ in candidates_with_size[:max_slides]]

    # Return in sorted order for reproducibility
    selected.sort(key=lambda x: x.name)

    logger.info(
        f"Found {len(candidates)} h5 files for {patient_id}, "
        f"using {len(selected)} (max_slides={max_slides})"
    )

    return selected


def load_h5_coords_and_features(h5_path: str) -> Tuple[np.ndarray, np.ndarray]:
    """
    Load patch coordinates and features from an h5 file.

    Args:
        h5_path: Path to h5 file.

    Returns:
        coords: [N, 2] array of (x, y) top-left patch coordinates.
        features: [N, D] array of patch features.
    """
    with h5py.File(h5_path, 'r') as f:
        # Load coordinates
        if 'coords' in f:
            coords = f['coords'][:]
        else:
            raise KeyError(
                f"No 'coords' key found in {h5_path}. "
                f"Available keys: {list(f.keys())}"
            )

        # Load features
        if 'features' in f:
            features = f['features'][:]
        elif 'feats' in f:
            features = f['feats'][:]
        else:
            key = list(f.keys())[0]
            features = f[key][:]

        features = features.squeeze()
        if features.ndim == 1:
            features = features.reshape(1, -1)

    return coords, features


def load_patient_slide_data(
    patient_id: str,
    h5_dir: str,
    slide_type_filter: str = 'DX',
    max_slides: int = 2,
) -> List[Dict]:
    """
    Load all slide data for a patient, preserving per-slide boundaries.

    This is the critical function that bridges the gap between the
    preprocessed (concatenated) features and the spatial coordinates.
    The returned slide list preserves the concatenation order so that
    feature index i in the model output maps to the correct slide and
    patch.

    Args:
        patient_id: TCGA patient ID.
        h5_dir: Directory with h5 files.
        slide_type_filter: Slide type filter.
        max_slides: Max slides (must match preprocessing).

    Returns:
        List of dicts, one per slide, in concatenation order:
            {
                'h5_path': Path,
                'slide_id': str,
                'coords': ndarray [N_slide, 2],
                'features': ndarray [N_slide, D],
                'n_patches': int,
                'feature_offset': int,  # start index in concatenated features
            }
    """
    h5_files = find_patient_h5_files(
        patient_id, h5_dir, slide_type_filter, max_slides
    )

    slides = []
    offset = 0

    for h5_path in h5_files:
        coords, features = load_h5_coords_and_features(str(h5_path))

        slide_id = h5_path.stem  # e.g., 'TCGA-A6-2671-01Z-00-DX1'

        slides.append({
            'h5_path': h5_path,
            'slide_id': slide_id,
            'coords': coords,
            'features': features,
            'n_patches': coords.shape[0],
            'feature_offset': offset,
        })

        offset += coords.shape[0]

    total_patches = sum(s['n_patches'] for s in slides)
    logger.info(
        f"Loaded {len(slides)} slides for {patient_id}: "
        f"{total_patches} total patches "
        f"(offsets: {[s['feature_offset'] for s in slides]})"
    )

    return slides


def _get_h5_feature_count(h5_file) -> int:
    """Get number of features/patches from an open h5 file."""
    if 'features' in h5_file:
        return h5_file['features'].shape[0]
    elif 'feats' in h5_file:
        return h5_file['feats'].shape[0]
    else:
        key = list(h5_file.keys())[0]
        return h5_file[key].shape[0]


# =====================================================================
# 1b. Loading from preprocessed .pt files (preferred)
# =====================================================================

def load_patient_spatial_data_from_pt(
    patient_id: str,
    wsi_features_dir: str,
) -> List[Dict]:
    """
    Load spatial data from the preprocessed .pt file directly.

    This is the preferred loading path when preprocess_wsi.py has been
    run with the coords patch applied. The .pt file contains features,
    coords, and slide boundary metadata — no h5 re-reading needed.

    Falls back gracefully if the .pt file uses the old format (bare
    tensor without coords).

    Args:
        patient_id: Patient ID.
        wsi_features_dir: Directory containing {patient_id}.pt files.

    Returns:
        List of slide dicts in concatenation order (same format as
        load_patient_slide_data), or None if coords unavailable.
    """
    import torch

    pt_path = os.path.join(wsi_features_dir, f"{patient_id}.pt")
    if not os.path.exists(pt_path):
        return None

    data = torch.load(pt_path, weights_only=False)

    # Old format: bare tensor — no coords available
    if isinstance(data, torch.Tensor):
        logger.warning(
            f"Old-format .pt file for {patient_id} (no coords). "
            f"Re-run preprocess_wsi to include coordinates."
        )
        return None

    # New format: dict with features, coords, slide_info
    coords = data.get('coords')
    slide_info = data.get('slide_info')

    if coords is None:
        logger.warning(f"No coords in .pt file for {patient_id}")
        return None

    coords_np = coords.numpy() if hasattr(coords, 'numpy') else np.asarray(coords)

    # If no slide_info, treat as single slide
    if slide_info is None:
        slide_info = [{
            'slide_id': patient_id,
            'h5_filename': f'{patient_id}.h5',
            'n_patches': coords_np.shape[0],
            'feature_offset': 0,
        }]

    # Build slide list with per-slide coord slicing
    slides = []
    for si in slide_info:
        offset = si['feature_offset']
        n = si['n_patches']
        slides.append({
            'h5_path': None,
            'slide_id': si['slide_id'],
            'coords': coords_np[offset:offset+n],
            'features': None,  # Not needed for visualization
            'n_patches': n,
            'feature_offset': offset,
        })

    total = sum(s['n_patches'] for s in slides)
    logger.info(
        f"Loaded spatial data from .pt for {patient_id}: "
        f"{len(slides)} slides, {total} patches"
    )

    return slides


# =====================================================================
# 2. Canvas construction
# =====================================================================

def build_canvas_from_wsi(
    wsi_path: str,
    coords: np.ndarray,
    patch_size: int = 256,
    level: int = 0,
    downsample: int = 1,
    coord_spacing: Optional[int] = None,
) -> np.ndarray:
    """
    Build tissue canvas by reading patch regions from a WSI file.

    Args:
        wsi_path: Path to WSI file (.svs, .ndpi, .tiff, etc.).
        coords: [N, 2] array of (x, y) top-left coordinates at level 0.
        patch_size: Patch size at extraction level (typically 256 for UNI-2h).
        level: OpenSlide level to read from (0 = highest resolution).
        downsample: Additional downsampling factor for the canvas.
        coord_spacing: Patch footprint in coordinate space. Auto-detected
            from coords if None. For UNI-2h with 40x level-0, this is
            typically 512 (256 pixels at 20x = 512 at 40x).

    Returns:
        canvas: RGB image array [H, W, 3].
    """
    if not HAS_OPENSLIDE:
        raise ImportError(
            "OpenSlide is required for WSI reading. "
            "Install with: pip install openslide-python"
        )

    if coord_spacing is None:
        coord_spacing = infer_coord_spacing(coords)
        logger.info(f"    Auto-detected coord spacing: {coord_spacing}")

    wsi = openslide.OpenSlide(wsi_path)

    # Read full patch footprint at level 0, then resize to target
    # coord_spacing is the footprint at level 0 (e.g., 512)
    read_size = coord_spacing
    effective_patch = int(coord_spacing / downsample)

    # Canvas dimensions
    max_x = int(coords[:, 0].max() / downsample) + effective_patch
    max_y = int(coords[:, 1].max() / downsample) + effective_patch

    canvas = np.full((max_y, max_x, 3), 240, dtype=np.uint8)

    from PIL import Image as PILImage

    for x, y in coords:
        region = wsi.read_region(
            (int(x), int(y)), level, (read_size, read_size)
        )
        patch_rgb = np.array(region.convert('RGB'))

        # Resize to effective canvas size
        if patch_rgb.shape[0] != effective_patch or patch_rgb.shape[1] != effective_patch:
            patch_pil = PILImage.fromarray(patch_rgb)
            patch_pil = patch_pil.resize(
                (effective_patch, effective_patch), PILImage.LANCZOS
            )
            patch_rgb = np.array(patch_pil)

        # Place on canvas
        cx = int(x / downsample)
        cy = int(y / downsample)
        ph, pw = patch_rgb.shape[:2]
        ph = min(ph, max_y - cy)
        pw = min(pw, max_x - cx)
        canvas[cy:cy+ph, cx:cx+pw] = patch_rgb[:ph, :pw]

    wsi.close()

    return canvas


def build_canvas_from_coords(
    coords: np.ndarray,
    patch_size: int = 256,
    downsample: int = 1,
    bg_color: int = 240,
    coord_spacing: Optional[int] = None,
) -> np.ndarray:
    """
    Build a blank canvas using coordinate layout only (no WSI needed).

    Useful for generating overlays when WSI files are not available.
    Patches appear as white rectangles on a grey background.

    Args:
        coords: [N, 2] array of (x, y) top-left coordinates.
        patch_size: Patch size at extraction level.
        downsample: Downsample factor.
        bg_color: Background grey value.
        coord_spacing: Patch footprint in coordinate space.
            Auto-detected from coords if None.

    Returns:
        canvas: RGB image array [H, W, 3].
    """
    if coord_spacing is None:
        coord_spacing = infer_coord_spacing(coords)

    effective_patch = int(coord_spacing / downsample)

    max_x = int(coords[:, 0].max() / downsample) + effective_patch
    max_y = int(coords[:, 1].max() / downsample) + effective_patch

    canvas = np.full((max_y, max_x, 3), bg_color, dtype=np.uint8)

    # Mark patch locations as white
    for x, y in coords:
        cx = int(x / downsample)
        cy = int(y / downsample)
        canvas[cy:cy+effective_patch, cx:cx+effective_patch] = 255

    return canvas


# =====================================================================
# 3. Overlay rendering
# =====================================================================

def render_prototype_overlay(
    coords: np.ndarray,
    assignments: np.ndarray,
    gate_weights: np.ndarray,
    patch_size: int = 256,
    downsample: int = 1,
    n_prototypes: Optional[int] = None,
    coord_spacing: Optional[int] = None,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Create RGBA overlay coloring each patch by prototype assignment.

    Uses uniform full opacity so prototype regions are clearly visible.
    Gate weight modulation is intentionally omitted because near-uniform
    weights (attention collapse) would make all patches equally faint.

    Args:
        coords: [N, 2] patch coordinates.
        assignments: [N] hard prototype assignment per patch.
        gate_weights: [K] prototype gate weights (reserved for future use).
        patch_size: Patch size at extraction level.
        downsample: Downsample factor.
        n_prototypes: Total number of prototypes (for colormap).
        coord_spacing: Patch footprint in coordinate space.

    Returns:
        overlay: RGBA image [H, W, 4] with prototype colors.
        cmap_dict: Dict mapping prototype_idx -> (R, G, B) tuple.
    """
    if coord_spacing is None:
        coord_spacing = infer_coord_spacing(coords)

    effective_patch = int(coord_spacing / downsample)
    max_x = int(coords[:, 0].max() / downsample) + effective_patch
    max_y = int(coords[:, 1].max() / downsample) + effective_patch

    if n_prototypes is None:
        n_prototypes = int(assignments.max()) + 1

    cmap_dict = _build_distinct_colormap(n_prototypes)

    overlay = np.zeros((max_y, max_x, 4), dtype=np.uint8)

    for i, (x, y) in enumerate(coords):
        proto_id = int(assignments[i])
        cx = int(x / downsample)
        cy = int(y / downsample)

        r, g, b = cmap_dict[proto_id]
        overlay[cy:cy+effective_patch, cx:cx+effective_patch] = [r, g, b, 255]

    return overlay, cmap_dict


def render_pathway_overlay(
    coords: np.ndarray,
    assignments: np.ndarray,
    cross_modal_attention: np.ndarray,
    gate_weights: np.ndarray,
    pathway_names: List[str],
    risk_group: str,
    fold_analysis_dir: str,
    patch_size: int = 256,
    downsample: int = 1,
    coord_spacing: Optional[int] = None,
) -> Tuple[np.ndarray, Dict[int, str], Dict[str, Tuple]]:
    """
    Risk-aware pathway overlay (Option C).

    For each prototype, selects the top pathway from the appropriate
    risk direction using per-fold rank analysis results.

    Args:
        coords: [N, 2] patch coordinates.
        assignments: [N] hard prototype assignment per patch.
        cross_modal_attention: [K, P] cross-modal attention matrix.
        gate_weights: [K] prototype gate weights (reserved for future use).
        pathway_names: Full pathway name list.
        risk_group: Patient's risk group ('High Risk' or 'Low Risk').
        fold_analysis_dir: Path to per-fold analysis CSVs.
        patch_size: Patch size.
        downsample: Downsample factor.
        coord_spacing: Patch footprint in coordinate space.

    Returns:
        overlay: RGBA image [H, W, 4].
        proto_pathway_map: Dict[proto_idx -> pathway_name].
        pathway_colors: Dict[pathway_name -> (R, G, B)].
    """
    if coord_spacing is None:
        coord_spacing = infer_coord_spacing(coords)

    n_prototypes = cross_modal_attention.shape[0]

    # Load per-prototype rank analysis and select top pathway per direction
    proto_pathway_map = _select_risk_aware_pathways(
        fold_analysis_dir, n_prototypes, risk_group
    )

    # Assign distinct colors to the unique pathways
    unique_pathways = sorted(set(proto_pathway_map.values()))
    pw_color_map = _build_distinct_colormap(len(unique_pathways))
    pathway_colors = {
        pw: pw_color_map[i]
        for i, pw in enumerate(unique_pathways)
    }

    effective_patch = int(coord_spacing / downsample)
    max_x = int(coords[:, 0].max() / downsample) + effective_patch
    max_y = int(coords[:, 1].max() / downsample) + effective_patch

    overlay = np.zeros((max_y, max_x, 4), dtype=np.uint8)

    for i, (x, y) in enumerate(coords):
        proto_id = int(assignments[i])
        cx = int(x / downsample)
        cy = int(y / downsample)

        pathway = proto_pathway_map.get(proto_id)
        if pathway is None:
            continue

        r, g, b = pathway_colors[pathway]
        overlay[cy:cy+effective_patch, cx:cx+effective_patch] = [r, g, b, 255]

    return overlay, proto_pathway_map, pathway_colors


def render_single_pathway_heatmap(
    coords: np.ndarray,
    assignments: np.ndarray,
    cross_modal_attention: np.ndarray,
    pathway_idx: int,
    patch_size: int = 256,
    downsample: int = 1,
    cmap_name: str = 'inferno',
    coord_spacing: Optional[int] = None,
    rank_transform: bool = False,
) -> Tuple[np.ndarray, float, float]:
    """
    Continuous heatmap for a single pathway — computational IHC stain.

    Each patch is colored by how strongly its prototype attends to the
    specified pathway.

    Args:
        coords: [N, 2] patch coordinates.
        assignments: [N] hard prototype assignment per patch.
        cross_modal_attention: [K, P] cross-modal attention.
        pathway_idx: Index of the target pathway.
        patch_size: Patch size.
        downsample: Downsample factor.
        cmap_name: Matplotlib colormap name.
        coord_spacing: Patch footprint in coordinate space.
        rank_transform: If True, map values to percentile ranks
            before coloring. Spreads the full colormap across the
            data regardless of the raw value distribution — useful
            when attention magnitudes are near-uniform.

    Returns:
        overlay: RGBA image [H, W, 4].
        vmin: Minimum value used for colorbar (raw or percentile).
        vmax: Maximum value used for colorbar (raw or percentile).
    """
    if coord_spacing is None:
        coord_spacing = infer_coord_spacing(coords)

    effective_patch = int(coord_spacing / downsample)
    max_x = int(coords[:, 0].max() / downsample) + effective_patch
    max_y = int(coords[:, 1].max() / downsample) + effective_patch

    # Per-prototype attention to this pathway
    proto_pw_attn = cross_modal_attention[:, pathway_idx]  # [K]

    # Per-patch attention (via assignment)
    patch_attn = proto_pw_attn[assignments.astype(int)]  # [N]

    if rank_transform:
        from scipy.stats import rankdata
        # Average rank, scaled to [0, 1] percentile
        patch_values = (rankdata(patch_attn) - 1) / max(len(patch_attn) - 1, 1)
        vmin, vmax = 0.0, 1.0
    else:
        patch_values = patch_attn
        vmin, vmax = float(patch_attn.min()), float(patch_attn.max())

    norm = Normalize(vmin=vmin, vmax=vmax)
    cmap = plt.cm.get_cmap(cmap_name)

    overlay = np.zeros((max_y, max_x, 4), dtype=np.uint8)

    for i, (x, y) in enumerate(coords):
        cx = int(x / downsample)
        cy = int(y / downsample)

        rgba = cmap(norm(patch_values[i]))
        overlay[cy:cy+effective_patch, cx:cx+effective_patch] = [
            int(rgba[0] * 255),
            int(rgba[1] * 255),
            int(rgba[2] * 255),
            255,
        ]

    return overlay, vmin, vmax


# =====================================================================
# 4. Pathway selection logic
# =====================================================================

def _select_risk_aware_pathways(
    analysis_dir: str,
    n_prototypes: int,
    risk_group: str,
) -> Dict[int, str]:
    """
    Select the top risk-direction-relevant pathway for each prototype
    from per-fold rank analysis results.

    For high-risk patients: select pathway with largest positive
    rank_difference (higher importance in high-risk group).
    For low-risk patients: select pathway with largest negative
    rank_difference (higher importance in low-risk group).

    Args:
        analysis_dir: Directory containing crossmodal_proto_*_rank_analysis.csv.
        n_prototypes: Number of prototypes.
        risk_group: 'High Risk' or 'Low Risk'.

    Returns:
        Dict[proto_idx -> pathway_name].
    """
    analysis_dir = Path(analysis_dir)
    proto_pathway_map = {}

    for proto_idx in range(n_prototypes):
        csv_path = analysis_dir / f'crossmodal_proto_{proto_idx}_rank_analysis.csv'

        if not csv_path.exists():
            logger.warning(f"Missing rank analysis for prototype {proto_idx}")
            continue

        df = pd.read_csv(csv_path)

        if 'High' in risk_group:
            # Top pathway with positive rank_difference (high-risk associated)
            candidates = df[df['rank_difference'] > 0]
            if len(candidates) == 0:
                candidates = df  # fallback to overall top
            top = candidates.nlargest(1, 'rank_difference')
        else:
            # Top pathway with negative rank_difference (low-risk associated)
            candidates = df[df['rank_difference'] < 0]
            if len(candidates) == 0:
                candidates = df
            top = candidates.nsmallest(1, 'rank_difference')

        if len(top) > 0:
            proto_pathway_map[proto_idx] = top.iloc[0]['entity']

    logger.info(
        f"Selected risk-aware pathways for {len(proto_pathway_map)} prototypes "
        f"(direction: {risk_group})"
    )

    return proto_pathway_map


# =====================================================================
# 5. Figure composition
# =====================================================================

def plot_spatial_figure(
    canvas: np.ndarray,
    overlays: List[Dict],
    output_path: str,
    patient_id: str,
    slide_id: str,
    risk_group: str,
    dpi: int = 300,
    overlay_alpha: float = 0.55,
):
    """
    Save each overlay as a separate figure in PDF, SVG, PNG at 300 DPI.

    Also saves a combined multi-panel overview figure.

    Output structure:
        {output_dir}/{patient_id}_HE.{pdf,svg,png}
        {output_dir}/{patient_id}_{overlay_slug}.{pdf,svg,png}
        {output_dir}/{patient_id}_spatial.pdf  (combined)
    """
    output_dir = Path(os.path.dirname(output_path) or '.')
    output_dir.mkdir(parents=True, exist_ok=True)

    aspect = canvas.shape[0] / canvas.shape[1]
    panel_w = 6
    panel_h = max(6, panel_w * aspect)

    # ── Individual H&E panel ─────────────────────────────────────
    fig_he, ax_he = plt.subplots(figsize=(panel_w, panel_h))
    ax_he.imshow(canvas)
    ax_he.set_title(f'H&E  |  {patient_id}', fontsize=11, fontweight='bold')
    ax_he.axis('off')
    plt.tight_layout()
    _save_multi_format(fig_he, str(output_dir / f'{patient_id}_HE'), dpi=dpi)
    plt.close(fig_he)
    logger.info(f"Saved H&E panel to {output_dir / patient_id}_HE.*")

    # ── Individual overlay panels ────────────────────────────────
    for i, ov in enumerate(overlays):
        title = ov.get('title', f'Overlay {i}')
        slug = (
            title.lower()
            .replace(' ', '_')
            .replace('(', '').replace(')', '')
            .replace('/', '_')
        )

        fig_ov, ax_ov = plt.subplots(figsize=(panel_w, panel_h))
        ax_ov.imshow(canvas)
        ax_ov.imshow(ov['image'], alpha=overlay_alpha)
        ax_ov.set_title(f'{title}  |  {risk_group}', fontsize=11, fontweight='bold')
        ax_ov.axis('off')

        # Categorical legend
        if 'legend' in ov and ov['legend']:
            handles = [
                mpatches.Patch(
                    facecolor=tuple(c / 255.0 for c in rgb),
                    edgecolor='black', linewidth=0.5, label=lbl,
                )
                for rgb, lbl in ov['legend']
            ]
            ax_ov.legend(
                handles=handles, loc='lower left',
                fontsize=6, framealpha=0.85, ncol=1,
                borderpad=0.3, handlelength=1.0, handletextpad=0.3,
            )

        # Continuous colorbar
        if 'colorbar' in ov and ov['colorbar']:
            cb = ov['colorbar']
            sm = plt.cm.ScalarMappable(
                cmap=cb['cmap'],
                norm=Normalize(vmin=cb['vmin'], vmax=cb['vmax']),
            )
            sm.set_array([])
            cbar = fig_ov.colorbar(sm, ax=ax_ov, fraction=0.046, pad=0.02)
            cbar.set_label(cb.get('label', ''), fontsize=8)

        plt.tight_layout()
        _save_multi_format(fig_ov, str(output_dir / f'{patient_id}_{slug}'), dpi=dpi)
        plt.close(fig_ov)
        logger.info(f"Saved overlay panel '{title}' to {output_dir / patient_id}_{slug}.*")

    # ── Combined multi-panel overview ────────────────────────────
    n_panels = 1 + len(overlays)
    fig, axes = plt.subplots(
        1, n_panels,
        figsize=(panel_w * n_panels, panel_h + 1.5),
        gridspec_kw={'wspace': 0.05},
    )
    if n_panels == 1:
        axes = [axes]

    axes[0].imshow(canvas)
    axes[0].set_title('H&E', fontsize=11, fontweight='bold')
    axes[0].axis('off')

    for i, ov in enumerate(overlays):
        ax = axes[i + 1]
        ax.imshow(canvas)
        ax.imshow(ov['image'], alpha=overlay_alpha)
        ax.set_title(ov.get('title', ''), fontsize=11, fontweight='bold')
        ax.axis('off')

        if 'legend' in ov and ov['legend']:
            handles = [
                mpatches.Patch(
                    facecolor=tuple(c / 255.0 for c in rgb),
                    edgecolor='black', linewidth=0.5, label=lbl,
                )
                for rgb, lbl in ov['legend']
            ]
            ax.legend(
                handles=handles, loc='lower left',
                fontsize=6, framealpha=0.85, ncol=1,
                borderpad=0.3, handlelength=1.0, handletextpad=0.3,
            )

        if 'colorbar' in ov and ov['colorbar']:
            cb = ov['colorbar']
            sm = plt.cm.ScalarMappable(
                cmap=cb['cmap'],
                norm=Normalize(vmin=cb['vmin'], vmax=cb['vmax']),
            )
            sm.set_array([])
            cbar = fig.colorbar(sm, ax=ax, fraction=0.046, pad=0.02)
            cbar.set_label(cb.get('label', ''), fontsize=8)

    fig.suptitle(
        f'{patient_id} | {risk_group}',
        fontsize=13, fontweight='bold', y=0.98,
    )
    fig.savefig(output_path, dpi=dpi, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    logger.info(f"Saved combined spatial figure to {output_path}")


# def plot_spatial_figure(
#     canvas: np.ndarray,
#     overlays: List[Dict],
#     output_path: str,
#     patient_id: str,
#     slide_id: str,
#     risk_group: str,
#     dpi: int = 300,
#     overlay_alpha: float = 0.55,
# ):
#     """
#     Compose a multi-panel spatial figure.
#
#     Each overlay dict has:
#         'image': RGBA ndarray (rendered with full alpha=255)
#         'title': str
#         'legend': optional list of (color_tuple, label) for categorical
#         'colorbar': optional dict with 'cmap', 'vmin', 'vmax', 'label'
#
#     The overlay_alpha parameter controls how much the H&E shows through.
#     0.55 is a good default — overlay is dominant but tissue is visible.
#
#     Args:
#         canvas: RGB tissue image [H, W, 3].
#         overlays: List of overlay dicts.
#         output_path: Save path.
#         patient_id: For title.
#         slide_id: For title.
#         risk_group: For title.
#         dpi: Output DPI.
#         overlay_alpha: Global overlay transparency (0=invisible, 1=opaque).
#     """
#     n_panels = 1 + len(overlays)  # original + overlays
#     fig_width = 6 * n_panels
#     aspect = canvas.shape[0] / canvas.shape[1]
#     fig_height = max(6, 6 * aspect) + 1.5  # extra for legends
#
#     fig, axes = plt.subplots(
#         1, n_panels, figsize=(fig_width, fig_height),
#         gridspec_kw={'wspace': 0.05}
#     )
#
#     if n_panels == 1:
#         axes = [axes]
#
#     # Panel 0: Original tissue
#     axes[0].imshow(canvas)
#     axes[0].set_title('H&E', fontsize=11, fontweight='bold')
#     axes[0].axis('off')
#
#     # Overlay panels
#     for i, ov in enumerate(overlays):
#         ax = axes[i + 1]
#         ax.imshow(canvas)
#         ax.imshow(ov['image'], alpha=overlay_alpha)
#         ax.set_title(ov.get('title', ''), fontsize=11, fontweight='bold')
#         ax.axis('off')
#
#         # Categorical legend
#         if 'legend' in ov and ov['legend']:
#             legend_handles = []
#             for color_rgb, label in ov['legend']:
#                 color_norm = tuple(c / 255.0 for c in color_rgb)
#                 legend_handles.append(
#                     mpatches.Patch(
#                         facecolor=color_norm, edgecolor='black',
#                         linewidth=0.5, label=label,
#                     )
#                 )
#             ax.legend(
#                 handles=legend_handles, loc='lower left',
#                 fontsize=6, framealpha=0.85, ncol=1,
#                 borderpad=0.3, handlelength=1.0, handletextpad=0.3,
#             )
#
#         # Continuous colorbar
#         if 'colorbar' in ov and ov['colorbar']:
#             cb_info = ov['colorbar']
#             sm = plt.cm.ScalarMappable(
#                 cmap=cb_info['cmap'],
#                 norm=Normalize(vmin=cb_info['vmin'], vmax=cb_info['vmax']),
#             )
#             sm.set_array([])
#             cbar = fig.colorbar(sm, ax=ax, fraction=0.046, pad=0.02)
#             cbar.set_label(cb_info.get('label', ''), fontsize=8)
#
#     fig.suptitle(
#         f'{patient_id}  |  {slide_id}  |  {risk_group}',
#         fontsize=13, fontweight='bold', y=0.98,
#     )
#
#     os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
#     fig.savefig(output_path, dpi=dpi, bbox_inches='tight', facecolor='white')
#     plt.close(fig)
#     logger.info(f"Saved spatial figure to {output_path}")


# =====================================================================
# 6. Main orchestrator
# =====================================================================

def generate_patient_spatial_viz(
    patient_id: str,
    attention_data: Dict,
    pathway_names: List[str],
    fold_analysis_dir: str,
    output_dir: str,
    risk_group: str,
    wsi_features_dir: Optional[str] = None,
    h5_dir: Optional[str] = None,
    wsi_dir: Optional[str] = None,
    wsi_path: Optional[str] = None,
    patch_size: int = 256,
    downsample: int = 4,
    slide_type_filter: str = 'DX',
    max_slides: int = 2,
    single_pathway_name: Optional[str] = None,
    single_pathway_idx: Optional[int] = None,
    rank_transform: bool = False,
):
    """
    Generate all spatial visualizations for a patient.

    Produces per-slide figures with:
        1. H&E tissue canvas
        2. Prototype assignment overlay
        3. Risk-aware pathway overlay (Option C)
        4. (Optional) Single-pathway attention heatmap

    Coordinate loading priority:
        1. wsi_features_dir — load from preprocessed .pt file (preferred,
           requires preprocess_wsi with coords patch)
        2. h5_dir — re-read original h5 files (fallback)

    Args:
        patient_id: TCGA patient ID.
        attention_data: Dict from attention_by_patient[patient_id].
        pathway_names: Full pathway name list.
        fold_analysis_dir: Per-fold analysis directory with rank CSVs.
        output_dir: Output directory for figures.
        risk_group: 'High Risk' or 'Low Risk'.
        wsi_features_dir: Directory with preprocessed .pt files (preferred).
        h5_dir: Directory with original h5 files (fallback).
        wsi_dir: Directory to search for WSI files (for tissue canvas).
        wsi_path: Explicit WSI path (single-slide only).
        patch_size: Patch size at extraction magnification.
        downsample: Downsample factor for rendering.
        slide_type_filter: H5 filename filter.
        max_slides: Max slides per patient.
        single_pathway_name: Name of pathway for single-pathway heatmap.
        single_pathway_idx: Index of pathway (alternative to name).
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Load slide data (prefer .pt, fallback to h5) ─────────────────
    slides = None

    if wsi_features_dir:
        slides = load_patient_spatial_data_from_pt(
            patient_id, wsi_features_dir
        )

    if slides is None and h5_dir:
        logger.info(f"Falling back to h5 loading for {patient_id}")
        slides = load_patient_slide_data(
            patient_id, h5_dir, slide_type_filter, max_slides
        )

    if slides is None:
        raise ValueError(
            f"Cannot load spatial data for {patient_id}. "
            f"Provide wsi_features_dir (preprocessed .pt with coords) "
            f"or h5_dir (original h5 files)."
        )

    # ── Extract attention signals ────────────────────────────────────
    pa = attention_data.get('patch_assignments', {})
    hard_assignments = np.asarray(pa.get('hard_assignments', pa.get('assignments', [])))
    gate_weights = np.asarray(pa.get('gate_weights', []))
    cross_modal = np.asarray(attention_data.get('cross_modal_attention', []))
    fusion_gate = np.asarray(attention_data.get('fusion_gate_weights', gate_weights))

    total_model_patches = len(hard_assignments)
    total_slide_patches = sum(s['n_patches'] for s in slides)

    if total_model_patches != total_slide_patches:
        logger.warning(
            f"Patch count mismatch: model has {total_model_patches} patches, "
            f"slides have {total_slide_patches}. Check preprocessing config "
            f"(max_slides={max_slides}, slide_type_filter='{slide_type_filter}')"
        )

    # ── Resolve single pathway ───────────────────────────────────────
    if single_pathway_name and single_pathway_idx is None:
        try:
            single_pathway_idx = pathway_names.index(single_pathway_name)
        except ValueError:
            logger.warning(
                f"Pathway '{single_pathway_name}' not found in pathway_names"
            )
            single_pathway_name = None

    if single_pathway_idx is not None and single_pathway_name is None:
        single_pathway_name = pathway_names[single_pathway_idx]

    # ── Generate per-slide visualizations ────────────────────────────
    for slide in slides:
        slide_id = slide['slide_id']
        offset = slide['feature_offset']
        n = slide['n_patches']
        coords = slide['coords']

        logger.info(
            f"  Rendering slide {slide_id} "
            f"(patches {offset}:{offset+n}, coords range: "
            f"x=[{coords[:,0].min()},{coords[:,0].max()}], "
            f"y=[{coords[:,1].min()},{coords[:,1].max()}])"
        )

        # Slice this slide's attention data
        slide_assignments = hard_assignments[offset:offset+n]
        slide_cross_modal = cross_modal  # [K, P] — shared across slides
        slide_gate_weights = gate_weights  # [K] — shared

        # ── Detect coordinate spacing ────────────────────────────────
        cs = infer_coord_spacing(coords)
        logger.info(f"    Coord spacing: {cs} (patch_size={patch_size})")

        # ── Build canvas ─────────────────────────────────────────────
        slide_wsi_path = _find_wsi_for_slide(slide_id, wsi_dir, wsi_path)

        if slide_wsi_path:
            logger.info(f"    Building canvas from WSI: {slide_wsi_path}")
            canvas = build_canvas_from_wsi(
                slide_wsi_path, coords, patch_size,
                downsample=downsample, coord_spacing=cs,
            )
        else:
            logger.info(f"    No WSI found, using coordinate-based canvas")
            canvas = build_canvas_from_coords(
                coords, patch_size,
                downsample=downsample, coord_spacing=cs,
            )

        overlays = []

        # ── Overlay 1: Prototype assignments ─────────────────────────
        proto_overlay, proto_colors = render_prototype_overlay(
            coords, slide_assignments, slide_gate_weights,
            patch_size, downsample, coord_spacing=cs,
        )
        proto_legend = [
            (proto_colors[i], f'Proto {i}')
            for i in sorted(set(slide_assignments.astype(int)))
        ]
        overlays.append({
            'image': proto_overlay,
            'title': 'Prototype Assignments',
            'legend': proto_legend,
        })

        # ── Overlay 2: Risk-aware pathway ────────────────────────────
        if len(slide_cross_modal) > 0 and pathway_names:
            pw_overlay, proto_pw_map, pw_colors = render_pathway_overlay(
                coords, slide_assignments, slide_cross_modal,
                slide_gate_weights, pathway_names, risk_group,
                fold_analysis_dir, patch_size, downsample,
                coord_spacing=cs,
            )

            # Build legend from proto-pathway map
            # Show unique pathways with truncated names
            seen = set()
            pw_legend = []
            for proto_idx in sorted(proto_pw_map.keys()):
                pw = proto_pw_map[proto_idx]
                if pw not in seen:
                    seen.add(pw)
                    display = pw[:35] + '...' if len(pw) > 35 else pw
                    pw_legend.append((pw_colors[pw], display))

            overlays.append({
                'image': pw_overlay,
                'title': f'Pathway ({risk_group.split()[0]}-Risk Direction)',
                'legend': pw_legend,
            })

        # ── Overlay 3: Single-pathway heatmap ────────────────────────
        if single_pathway_idx is not None and len(slide_cross_modal) > 0:
            display_name = single_pathway_name[:40]

            # Raw attention version
            ihc_overlay, vmin, vmax = render_single_pathway_heatmap(
                coords, slide_assignments, slide_cross_modal,
                single_pathway_idx, patch_size, downsample,
                coord_spacing=cs, rank_transform=False,
            )
            overlays.append({
                'image': ihc_overlay,
                'title': f'{display_name}',
                'colorbar': {
                    'cmap': 'inferno',
                    'vmin': vmin,
                    'vmax': vmax,
                    'label': 'Attention',
                },
            })

            # Rank-transformed version (percentile)
            if rank_transform:
                rank_overlay, rvmin, rvmax = render_single_pathway_heatmap(
                    coords, slide_assignments, slide_cross_modal,
                    single_pathway_idx, patch_size, downsample,
                    coord_spacing=cs, rank_transform=True,
                )
                overlays.append({
                    'image': rank_overlay,
                    'title': f'{display_name} (rank)',
                    'colorbar': {
                        'cmap': 'inferno',
                        'vmin': rvmin,
                        'vmax': rvmax,
                        'label': 'Percentile',
                    },
                })

        # ── Extract and visualize prototype exemplar patches ─────
        try:
            exemplars = extract_exemplar_patches(
                patient_id=patient_id,
                attention_data=attention_data,
                coords=coords,
                canvas=canvas,
                downsample=downsample,
                coord_spacing=cs,
                top_k_protos=5,
                n_patches_per_proto=5,
                wsi_path=slide_wsi_path,
                patch_size=patch_size,
            )

            if exemplars:
                weights = np.asarray(
                    pa.get('gate_weights',
                           attention_data.get('fusion_gate_weights', []))
                )

                # Full exemplar grid for this slide
                plot_prototype_exemplars(
                    exemplars=exemplars,
                    importance_weights=weights,
                    output_dir=str(output_dir),
                    slide_id=slide_id,
                    proto_colors=proto_colors,
                    dpi=300,
                )

                # # Exemplar strip for prototype assignment overlay
                # visible_protos = sorted(set(slide_assignments.astype(int)))
                # plot_overlay_exemplar_strip(
                #     exemplars=exemplars,
                #     visible_protos=visible_protos,
                #     importance_weights=weights,
                #     overlay_title='Prototype Assignments',
                #     output_dir=str(output_dir),
                #     slide_id=slide_id,
                #     proto_colors=proto_colors,
                # )

        except Exception as e:
            logger.warning(f"Exemplar extraction failed for {slide_id}: {e}")

        # ── Compose and save ─────────────────────────────────────────
        output_path = output_dir / f'{patient_id}_spatial.pdf'
        plot_spatial_figure(
            canvas, overlays, str(output_path),
            patient_id, slide_id, risk_group,
        )

    logger.info(f"Spatial visualization complete for {patient_id}")


def _find_wsi_for_slide(
    slide_id: str,
    wsi_dir: Optional[str],
    wsi_path: Optional[str],
) -> Optional[str]:
    """
    Try to find a WSI file matching a slide ID.

    Args:
        slide_id: Slide identifier (e.g., 'TCGA-A6-2671-01Z-00-DX1').
        wsi_dir: Directory to search for WSI files.
        wsi_path: Explicit path (returned directly if provided).

    Returns:
        Path to WSI file, or None if not found.
    """
    if wsi_path and os.path.exists(wsi_path):
        return wsi_path

    if wsi_dir is None:
        return None

    wsi_dir = Path(wsi_dir)
    wsi_extensions = ['.svs', '.ndpi', '.tiff', '.tif', '.mrxs']

    for ext in wsi_extensions:
        candidate = wsi_dir / f'{slide_id}{ext}'
        if candidate.exists():
            return str(candidate)

    # Fuzzy match: slide_id might be a prefix
    for ext in wsi_extensions:
        matches = list(wsi_dir.glob(f'{slide_id}*{ext}'))
        if matches:
            return str(matches[0])

    return None


# =====================================================================
# 7. Batch generation helper
# =====================================================================

def generate_batch_spatial_viz(
    patient_ids: List[str],
    attention_by_patient: Dict[str, Dict],
    predictions: 'pd.DataFrame',
    pathway_names: List[str],
    fold_analysis_dir: str,
    output_dir: str,
    wsi_features_dir: Optional[str] = None,
    h5_dir: Optional[str] = None,
    wsi_dir: Optional[str] = None,
    patch_size: int = 256,
    downsample: int = 4,
    single_pathway_name: Optional[str] = None,
    **kwargs,
):
    """
    Generate spatial visualizations for a batch of patients.

    Convenience wrapper for generate_patient_spatial_viz that
    automatically looks up risk group from predictions.

    Args:
        patient_ids: List of patient IDs to visualize.
        attention_by_patient: Full attention dict.
        predictions: DataFrame with patient_id and risk_group columns.
        pathway_names: Pathway names.
        fold_analysis_dir: Per-fold analysis directory.
        output_dir: Output directory.
        wsi_features_dir: Preprocessed .pt directory (preferred).
        h5_dir: Original h5 directory (fallback).
        wsi_dir: Optional WSI directory.
        patch_size: Patch size.
        downsample: Downsample factor.
        single_pathway_name: Optional pathway for IHC overlay.
        **kwargs: Additional kwargs for generate_patient_spatial_viz.
    """
    risk_map = dict(
        zip(predictions['patient_id'], predictions['risk_group'])
    )

    for pid in patient_ids:
        if pid not in attention_by_patient:
            logger.warning(f"No attention data for {pid}, skipping")
            continue

        risk_group = risk_map.get(pid, 'Unknown')
        logger.info(f"\nGenerating spatial viz for {pid} ({risk_group})")

        try:
            generate_patient_spatial_viz(
                patient_id=pid,
                attention_data=attention_by_patient[pid],
                pathway_names=pathway_names,
                fold_analysis_dir=fold_analysis_dir,
                output_dir=os.path.join(output_dir, pid),
                risk_group=risk_group,
                wsi_features_dir=wsi_features_dir,
                h5_dir=h5_dir,
                wsi_dir=wsi_dir,
                patch_size=patch_size,
                downsample=downsample,
                single_pathway_name=single_pathway_name,
                **kwargs,
            )
        except Exception as e:
            logger.error(f"Failed for {pid}: {e}")